### ISSUE TITLE
 Supplementary Material

### ISSUE THREAD

**Issue by milliema** [SY-Xuan/DSCL#1]
Thanks for the work!
I am very interested in the mathematical analysis section, where can I access the supplementary material?

**Comment by SY-Xuan** [comment]
Would you mind give me your email address? I will send it to you.

**Comment by milliema** [comment]
> Would you mind give me your email address? I will send it to you.

My email address is jimohanqiu@hotmail.com, thanks a lot!

**Comment by LiuZS10** [comment]
Dear authors, 
If it is convenient for you, could you please send the supplementary materials to my email address at zsliu10@gmail.com? I promise they will be used only for research purposes. Thanks!

**Comment by SY-Xuan** [comment]
We upload the supplementary material. You can refer to this repo.

**Comment by LiuZS10** [comment]
Thanks!
